### ISSUE TITLE
Bundle install failed on  rails 5.2

### ISSUE THREAD

**Issue by xlanex6** [techgurupezza/devise_materialize#4]
## Expected Behavior
bundle install == green 

## Actual Behavior

```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (= 5.2.0)

  In Gemfile:
    devise was resolved to 4.4.3, which depends on
      railties (< 6.0, >= 4.1.0)

    devise_materialize (~> 1.1.1) was resolved to 1.1.1, which depends on
      railties (< 5.2, >= 4.1.0)

    material_icons was resolved to 2.2.1, which depends on
      railties (>= 3.2)

    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      railties (= 5.2.0)

    devise was resolved to 4.4.3, which depends on
      responders was resolved to 2.4.0, which depends on
        railties (< 5.3, >= 4.2.0)

    sass-rails was resolved to 5.0.7, which depends on
      railties (< 6, >= 4.0.0)

    web-console (>= 3.6.2, ~> 3.6) was resolved to 3.6.2, which depends on
      railties (>= 5.0)

    webpacker was resolved to 3.5.3, which depends on
      railties (>= 4.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

``
## Steps to Reproduce

my full gem file

```
source 'https://rubygems.org'
ruby '2.5.0'

gem 'bootsnap', require: false
gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg', '~> 0.21'
gem 'puma'
gem 'rails', '5.2.0'
gem 'redis'
gem 'turbolinks', '~> 5.1', '>= 5.1.1'

gem 'autoprefixer-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'
gem 'material_icons'
gem 'materialize-sass'

gem 'forest_liana'
gem 'omniauth-facebook'
gem 'pundit', '~> 1.1'
gem 'simple_token_authentication'
gem 'redcarpet'
gem "devise_materialize", "~>1.1.1"

group :development do
  gem 'web-console', '~> 3.6', '>= 3.6.2'
  gem 'annotate', '~> 2.7', '>= 2.7.3'
  gem 'bullet', '~> 5.7', '>= 5.7.5'
  gem 'faker', '~> 1.8', '>= 1.8.7'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

```
## Browsers Used
- [ ] Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Opera


## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by cgibsonmm** [comment]
+1

**Comment by cgibsonmm** [comment]
I created a pull request that has fixed this issue on and will work on your version of ruby.
